### ISSUE TITLE
Opening chest would cause server lag.

### ISSUE THREAD

**Issue by Cordium1990** [xcodian/PerPlayerLoot#2]
When open a chest in the dungen of wild.During that time, time would frozen in that moment,and after I opened that chest,evething starts going on.

**Comment by xcodian** [comment]
Hello, sorry for the late reply - it is very strange that this plugin would be causing any performance issues, as it actually does surprisingly little in order to function.

If possible, could you let me know about:
1. What hardware is your server running on?
2. What is the file size of "perplayerloot.db" file in the tshock folder?
3. Does the same issue occur with regular chests?
4. Do you have any other plugins installed?

Hope I can help you out. :)

**Comment by Cordium1990** [comment]
sorry mister, my bad, after I check these 4 questions, I found that lag was because I have two maps use the same name. And I should delete the SQLite file after I changed map. After I done that, there's another issue comes out, when I open a chest which I have never opened before would cause a few seconds' lag. After the first open, the issue disappears.
For your questions' answer
1.Inter Xeon CPU E5-2690 V2 3.00Ghz with 16gb ram.
2 2.15mb
3 no
4 no, I have tested it with no plugin install, and it seems with fewer player, the lag would shorter.

**Comment by vosdbk** [comment]
we have the same problem!

1. intel xeon e5645, 16gb ram
2. perplayerloot.sqlite, 144kb
3. no, just with new found chest
4. no, just perperlayloot installed

when one player find a chest and trying to open it, all players would be stoped until a lot of server notice displayed, costs about 5~10 secs. as pic no.1 below.
![1](https://github.com/xxcodianxx/PerPlayerLoot/assets/2115591/c363ccbc-33e4-4ab8-bdd3-1f01c0973606)

server log shows that has throwed an exception, as pic no.2
![2](https://github.com/xxcodianxx/PerPlayerLoot/assets/2115591/17d98c10-43d7-4d2d-8fa5-e3dfcc97636d)

**Comment by xcodian** [comment]
Thanks for the reports guys, I'll take a look at what's causing the issue.
